### ISSUE TITLE
Remove dependency to cloudwatch_metrics_collector

### ISSUE THREAD

**Issue by juanrh** [aws-robotics/aws-robomaker-sample-application-persondetection#9]
The cloudwatch_metrics_collector node is not used on [monitoring.launch](https://github.com/aws-robotics/aws-robomaker-sample-application-persondetection/blob/master/robot_ws/src/person_detection_robot/launch/monitoring.launch), only `cloudwatch_logger`. However the comment in that launch file refers to " CloudWatch Metrics" and [package.xml](https://github.com/aws-robotics/aws-robomaker-sample-application-persondetection/blob/master/robot_ws/src/person_detection_robot/package.xml) also has a dependency to `cloudwatch_metrics_collector`

**Comment by AAlon** [comment]
Removed unused dependencies in #18.
